version: '3.8'

services:
  # Healthcare Backend API
  api:
    build: .
    ports:
      - "3001:3001"
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=healthcare_db
      - SERVER_PORT=3001
    depends_on:
      - postgres
    volumes:
      - ./uploads:/root/uploads
      - ./user_photos:/root/user_photos
    networks:
      - healthcare-network

  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: healthcare_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - healthcare-network

  # pgAdmin for database management (optional)
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@healthcare.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - healthcare-network

volumes:
  postgres_data:

networks:
  healthcare-network:
    driver: bridge
