version: '3.8'
services:
  backend:
    image: backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8001:8001
    environment:
      - GOLANG_BACKEND_URL=http://golang-backend:8000
    volumes:
      - .:/code/
    command: uvicorn main:app --host 0.0.0.0 --port 8001
    env_file:
      - .env

volumes:
  pg-data:
    driver: local

networks:
  default:
    driver: bridge