[project]
name = "search-engine"
version = "0.0.1"
requires-python = ">=3.11"
dependencies = ["fastapi", "openai", "pydantic-settings", "uvicorn", "requests", "psycopg2-binary"]


[project.optional-dependencies]
dev = ["ruff", "black"]