export * from './components';
export * from './pages';
export * from './hooks';
export * from './services';
export * from './utils';
export { default as PatientListPage } from './pages/PatientListPage';
export { default as PatientDetailsPage } from './pages/PatientDetailsPage';
export { default as PatientList } from './components/PatientList';
export { default as PatientCard } from './components/PatientCard';
export { default as PatientSearch } from './components/PatientSearch';
export { default as PatientDetails } from './components/PatientDetails';
export { default as usePatientManagement } from './hooks/usePatientManagement';
export { default as patientService } from './services/patientService';
